/*
# Kirinyaga Healthcare Workers Cafeteria POS — Core Schema

## Overview
Creates the complete relational schema for the cafeteria POS and management system.
All tables use RLS with authenticated-only access (this app has a sign-in screen).

## Tables Created

### Identity & Access
- `profiles` — staff accounts linked to auth.users, with role (super_admin/admin/cashier/storekeeper/accountant/auditor), employee_id, salary, status
- `stores` — multiple locations (main store, cafeteria, kitchen, branches)
- `audit_logs` — immutable record of sensitive operations (user, action, entity, old/new values)
- `settings` — key/value app configuration (M-Pesa config stored here, encrypted at app layer)
- `notifications` — in-app alerts (low stock, failed payments, etc.)

### Catalog & Inventory
- `categories` — product categories
- `products` — menu items with SKU, barcode, buying/selling price, image, allow_negative_stock flag
- `inventory` — per-product, per-store stock levels with minimum_stock
- `inventory_movements` — traceable stock changes (purchase/sale/adjustment/damage/expiry/transfer/return) with previous/new quantity, reason, user

### Customers & Dining
- `customers` — customer records with phone, employee_number, type (staff/visitor/student)
- `tables` — dining tables with status (available/occupied/payment_pending/paid/closed)
- `tabs` — open dine-in bills linked to table, customer, cashier, shift
- `tab_items` — products on a tab with quantity and price

### Sales & Payments
- `shifts` — cashier shifts with shift_number, opening/closing time, status, opening_cash (always 0 for M-Pesa only)
- `sales` — sales records with receipt_number, shift, cashier, customer, table, totals, status, payment_status
- `sale_items` — line items per sale
- `payments` — payment records (mpesa_stk/mpesa_paybill) with status, phone, mpesa_receipt_number, checkout/merchant request IDs
- `mpesa_transactions` — Daraja API transaction log with result_code, reconciliation_status

### Procurement & Finance
- `suppliers` — supplier records with outstanding balance
- `purchases` — purchase orders with supplier, invoice, payment status, balance
- `purchase_items` — line items per purchase
- `expenses` — expense records with category, amount, attachment
- `payroll` — salary records per employee per pay period

## Security
- RLS enabled on ALL tables
- All policies scoped TO authenticated
- profiles: users can read/update own profile; all authenticated can read profiles (staff directory)
- All business tables: authenticated users can read; writes restricted by application-level permission checks
  (RLS allows authenticated writes — fine-grained permission enforcement is in the app layer + audit logs)
- audit_logs: authenticated can read; inserts allowed for authenticated (system writes via service role)

## Important Notes
1. This is a multi-user app with sign-in. All policies are `TO authenticated`.
2. profiles.id references auth.users.id with DEFAULT auth.uid() so inserts work.
3. shift_number is auto-incremented per cashier via a sequence.
4. receipt_number format: RCP-YYYYMMDD-NNN generated by app.
5. M-Pesa credentials stored in settings table as encrypted values — secrets never in frontend.
*/

-- ============ PROFILES ============
CREATE TABLE IF NOT EXISTS profiles (
  id uuid PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  email text NOT NULL,
  full_name text NOT NULL,
  employee_id text UNIQUE NOT NULL,
  phone text,
  position text,
  role text NOT NULL DEFAULT 'cashier' CHECK (role IN ('super_admin','admin','cashier','storekeeper','accountant','auditor')),
  salary numeric(12,2) DEFAULT 0,
  status text NOT NULL DEFAULT 'active' CHECK (status IN ('active','inactive')),
  date_joined date DEFAULT CURRENT_DATE,
  created_at timestamptz DEFAULT now()
);
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "profiles_select_authenticated" ON profiles;
CREATE POLICY "profiles_select_authenticated" ON profiles FOR SELECT TO authenticated USING (true);

DROP POLICY IF EXISTS "profiles_insert_own" ON profiles;
CREATE POLICY "profiles_insert_own" ON profiles FOR INSERT TO authenticated WITH CHECK (auth.uid() = id);

DROP POLICY IF EXISTS "profiles_update_own" ON profiles;
CREATE POLICY "profiles_update_own" ON profiles FOR UPDATE TO authenticated USING (auth.uid() = id) WITH CHECK (auth.uid() = id);

-- ============ STORES ============
CREATE TABLE IF NOT EXISTS stores (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name text NOT NULL,
  type text NOT NULL DEFAULT 'cafeteria' CHECK (type IN ('main_store','cafeteria','kitchen','branch')),
  location text,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamptz DEFAULT now()
);
ALTER TABLE stores ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "stores_select" ON stores; CREATE POLICY "stores_select" ON stores FOR SELECT TO authenticated USING (true);
DROP POLICY IF EXISTS "stores_insert" ON stores; CREATE POLICY "stores_insert" ON stores FOR INSERT TO authenticated WITH CHECK (true);
DROP POLICY IF EXISTS "stores_update" ON stores; CREATE POLICY "stores_update" ON stores FOR UPDATE TO authenticated USING (true) WITH CHECK (true);

-- ============ CATEGORIES ============
CREATE TABLE IF NOT EXISTS categories (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name text NOT NULL,
  description text,
  created_at timestamptz DEFAULT now()
);
ALTER TABLE categories ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "categories_select" ON categories; CREATE POLICY "categories_select" ON categories FOR SELECT TO authenticated USING (true);
DROP POLICY IF EXISTS "categories_insert" ON categories; CREATE POLICY "categories_insert" ON categories FOR INSERT TO authenticated WITH CHECK (true);
DROP POLICY IF EXISTS "categories_update" ON categories; CREATE POLICY "categories_update" ON categories FOR UPDATE TO authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "categories_delete" ON categories; CREATE POLICY "categories_delete" ON categories FOR DELETE TO authenticated USING (true);

-- ============ PRODUCTS ============
CREATE TABLE IF NOT EXISTS products (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name text NOT NULL,
  sku text UNIQUE NOT NULL,
  barcode text,
  category_id uuid REFERENCES categories(id) ON DELETE SET NULL,
  buying_price numeric(12,2) NOT NULL DEFAULT 0,
  selling_price numeric(12,2) NOT NULL DEFAULT 0,
  unit text NOT NULL DEFAULT 'each',
  image_url text,
  description text,
  is_active boolean NOT NULL DEFAULT true,
  allow_negative_stock boolean NOT NULL DEFAULT false,
  created_at timestamptz DEFAULT now()
);
ALTER TABLE products ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "products_select" ON products; CREATE POLICY "products_select" ON products FOR SELECT TO authenticated USING (true);
DROP POLICY IF EXISTS "products_insert" ON products; CREATE POLICY "products_insert" ON products FOR INSERT TO authenticated WITH CHECK (true);
DROP POLICY IF EXISTS "products_update" ON products; CREATE POLICY "products_update" ON products FOR UPDATE TO authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "products_delete" ON products; CREATE POLICY "products_delete" ON products FOR DELETE TO authenticated USING (true);
CREATE INDEX IF NOT EXISTS idx_products_category ON products(category_id);
CREATE INDEX IF NOT EXISTS idx_products_sku ON products(sku);
CREATE INDEX IF NOT EXISTS idx_products_name ON products(name);

-- ============ INVENTORY ============
CREATE TABLE IF NOT EXISTS inventory (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  product_id uuid NOT NULL REFERENCES products(id) ON DELETE CASCADE,
  store_id uuid NOT NULL REFERENCES stores(id) ON DELETE CASCADE,
  quantity integer NOT NULL DEFAULT 0,
  minimum_stock integer NOT NULL DEFAULT 5,
  UNIQUE(product_id, store_id)
);
ALTER TABLE inventory ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "inventory_select" ON inventory; CREATE POLICY "inventory_select" ON inventory FOR SELECT TO authenticated USING (true);
DROP POLICY IF EXISTS "inventory_insert" ON inventory; CREATE POLICY "inventory_insert" ON inventory FOR INSERT TO authenticated WITH CHECK (true);
DROP POLICY IF EXISTS "inventory_update" ON inventory; CREATE POLICY "inventory_update" ON inventory FOR UPDATE TO authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "inventory_delete" ON inventory; CREATE POLICY "inventory_delete" ON inventory FOR DELETE TO authenticated USING (true);
CREATE INDEX IF NOT EXISTS idx_inventory_product ON inventory(product_id);
CREATE INDEX IF NOT EXISTS idx_inventory_store ON inventory(store_id);

-- ============ INVENTORY MOVEMENTS ============
CREATE TABLE IF NOT EXISTS inventory_movements (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  product_id uuid NOT NULL REFERENCES products(id) ON DELETE CASCADE,
  store_id uuid NOT NULL REFERENCES stores(id) ON DELETE CASCADE,
  movement_type text NOT NULL CHECK (movement_type IN ('purchase','sale','adjustment','damage','expiry','transfer','return')),
  quantity integer NOT NULL,
  previous_quantity integer NOT NULL,
  new_quantity integer NOT NULL,
  reason text,
  user_id uuid NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  created_at timestamptz DEFAULT now()
);
ALTER TABLE inventory_movements ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "movements_select" ON inventory_movements; CREATE POLICY "movements_select" ON inventory_movements FOR SELECT TO authenticated USING (true);
DROP POLICY IF EXISTS "movements_insert" ON inventory_movements; CREATE POLICY "movements_insert" ON inventory_movements FOR INSERT TO authenticated WITH CHECK (true);
CREATE INDEX IF NOT EXISTS idx_movements_product ON inventory_movements(product_id);
CREATE INDEX IF NOT EXISTS idx_movements_created ON inventory_movements(created_at);

-- ============ CUSTOMERS ============
CREATE TABLE IF NOT EXISTS customers (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name text NOT NULL,
  phone text NOT NULL,
  employee_number text,
  customer_type text NOT NULL DEFAULT 'staff' CHECK (customer_type IN ('staff','visitor','student')),
  created_at timestamptz DEFAULT now()
);
ALTER TABLE customers ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "customers_select" ON customers; CREATE POLICY "customers_select" ON customers FOR SELECT TO authenticated USING (true);
DROP POLICY IF EXISTS "customers_insert" ON customers; CREATE POLICY "customers_insert" ON customers FOR INSERT TO authenticated WITH CHECK (true);
DROP POLICY IF EXISTS "customers_update" ON customers; CREATE POLICY "customers_update" ON customers FOR UPDATE TO authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "customers_delete" ON customers; CREATE POLICY "customers_delete" ON customers FOR DELETE TO authenticated USING (true);
CREATE INDEX IF NOT EXISTS idx_customers_phone ON customers(phone);
CREATE INDEX IF NOT EXISTS idx_customers_name ON customers(name);

-- ============ TABLES (Dining) ============
CREATE TABLE IF NOT EXISTS tables (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  table_number text NOT NULL,
  status text NOT NULL DEFAULT 'available' CHECK (status IN ('available','occupied','payment_pending','paid','closed')),
  store_id uuid NOT NULL REFERENCES stores(id) ON DELETE CASCADE,
  created_at timestamptz DEFAULT now()
);
ALTER TABLE tables ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "tables_select" ON tables; CREATE POLICY "tables_select" ON tables FOR SELECT TO authenticated USING (true);
DROP POLICY IF EXISTS "tables_insert" ON tables; CREATE POLICY "tables_insert" ON tables FOR INSERT TO authenticated WITH CHECK (true);
DROP POLICY IF EXISTS "tables_update" ON tables; CREATE POLICY "tables_update" ON tables FOR UPDATE TO authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "tables_delete" ON tables; CREATE POLICY "tables_delete" ON tables FOR DELETE TO authenticated USING (true);

-- ============ SHIFTS ============
CREATE TABLE IF NOT EXISTS shifts (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  cashier_id uuid NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  shift_number integer NOT NULL,
  opening_time timestamptz NOT NULL DEFAULT now(),
  closing_time timestamptz,
  status text NOT NULL DEFAULT 'open' CHECK (status IN ('open','closed')),
  opening_cash numeric(12,2) NOT NULL DEFAULT 0,
  device_info text,
  created_at timestamptz DEFAULT now()
);
ALTER TABLE shifts ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "shifts_select" ON shifts; CREATE POLICY "shifts_select" ON shifts FOR SELECT TO authenticated USING (true);
DROP POLICY IF EXISTS "shifts_insert" ON shifts; CREATE POLICY "shifts_insert" ON shifts FOR INSERT TO authenticated WITH CHECK (true);
DROP POLICY IF EXISTS "shifts_update" ON shifts; CREATE POLICY "shifts_update" ON shifts FOR UPDATE TO authenticated USING (true) WITH CHECK (true);
CREATE INDEX IF NOT EXISTS idx_shifts_cashier ON shifts(cashier_id);
CREATE INDEX IF NOT EXISTS idx_shifts_status ON shifts(status);

-- ============ TABS ============
CREATE TABLE IF NOT EXISTS tabs (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  table_id uuid REFERENCES tables(id) ON DELETE SET NULL,
  customer_id uuid REFERENCES customers(id) ON DELETE SET NULL,
  cashier_id uuid NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  shift_id uuid NOT NULL REFERENCES shifts(id) ON DELETE CASCADE,
  status text NOT NULL DEFAULT 'open' CHECK (status IN ('open','payment_pending','paid','closed')),
  total numeric(12,2) NOT NULL DEFAULT 0,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);
ALTER TABLE tabs ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "tabs_select" ON tabs; CREATE POLICY "tabs_select" ON tabs FOR SELECT TO authenticated USING (true);
DROP POLICY IF EXISTS "tabs_insert" ON tabs; CREATE POLICY "tabs_insert" ON tabs FOR INSERT TO authenticated WITH CHECK (true);
DROP POLICY IF EXISTS "tabs_update" ON tabs; CREATE POLICY "tabs_update" ON tabs FOR UPDATE TO authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "tabs_delete" ON tabs; CREATE POLICY "tabs_delete" ON tabs FOR DELETE TO authenticated USING (true);
CREATE INDEX IF NOT EXISTS idx_tabs_status ON tabs(status);

-- ============ TAB ITEMS ============
CREATE TABLE IF NOT EXISTS tab_items (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tab_id uuid NOT NULL REFERENCES tabs(id) ON DELETE CASCADE,
  product_id uuid NOT NULL REFERENCES products(id) ON DELETE CASCADE,
  quantity integer NOT NULL DEFAULT 1,
  unit_price numeric(12,2) NOT NULL,
  subtotal numeric(12,2) NOT NULL,
  created_at timestamptz DEFAULT now()
);
ALTER TABLE tab_items ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "tab_items_select" ON tab_items; CREATE POLICY "tab_items_select" ON tab_items FOR SELECT TO authenticated USING (true);
DROP POLICY IF EXISTS "tab_items_insert" ON tab_items; CREATE POLICY "tab_items_insert" ON tab_items FOR INSERT TO authenticated WITH CHECK (true);
DROP POLICY IF EXISTS "tab_items_update" ON tab_items; CREATE POLICY "tab_items_update" ON tab_items FOR UPDATE TO authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "tab_items_delete" ON tab_items; CREATE POLICY "tab_items_delete" ON tab_items FOR DELETE TO authenticated USING (true);

-- ============ SALES ============
CREATE TABLE IF NOT EXISTS sales (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  receipt_number text UNIQUE NOT NULL,
  shift_id uuid NOT NULL REFERENCES shifts(id) ON DELETE CASCADE,
  cashier_id uuid NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  customer_id uuid REFERENCES customers(id) ON DELETE SET NULL,
  table_id uuid REFERENCES tables(id) ON DELETE SET NULL,
  tab_id uuid REFERENCES tabs(id) ON DELETE SET NULL,
  subtotal numeric(12,2) NOT NULL DEFAULT 0,
  total numeric(12,2) NOT NULL DEFAULT 0,
  status text NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','paid','void','refunded')),
  payment_status text NOT NULL DEFAULT 'pending' CHECK (payment_status IN ('pending','success','failed','cancelled','timeout')),
  mpesa_reference text,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);
ALTER TABLE sales ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "sales_select" ON sales; CREATE POLICY "sales_select" ON sales FOR SELECT TO authenticated USING (true);
DROP POLICY IF EXISTS "sales_insert" ON sales; CREATE POLICY "sales_insert" ON sales FOR INSERT TO authenticated WITH CHECK (true);
DROP POLICY IF EXISTS "sales_update" ON sales; CREATE POLICY "sales_update" ON sales FOR UPDATE TO authenticated USING (true) WITH CHECK (true);
CREATE INDEX IF NOT EXISTS idx_sales_receipt ON sales(receipt_number);
CREATE INDEX IF NOT EXISTS idx_sales_shift ON sales(shift_id);
CREATE INDEX IF NOT EXISTS idx_sales_cashier ON sales(cashier_id);
CREATE INDEX IF NOT EXISTS idx_sales_created ON sales(created_at);
CREATE INDEX IF NOT EXISTS idx_sales_status ON sales(status);

-- ============ SALE ITEMS ============
CREATE TABLE IF NOT EXISTS sale_items (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  sale_id uuid NOT NULL REFERENCES sales(id) ON DELETE CASCADE,
  product_id uuid NOT NULL REFERENCES products(id) ON DELETE CASCADE,
  quantity integer NOT NULL,
  unit_price numeric(12,2) NOT NULL,
  subtotal numeric(12,2) NOT NULL
);
ALTER TABLE sale_items ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "sale_items_select" ON sale_items; CREATE POLICY "sale_items_select" ON sale_items FOR SELECT TO authenticated USING (true);
DROP POLICY IF EXISTS "sale_items_insert" ON sale_items; CREATE POLICY "sale_items_insert" ON sale_items FOR INSERT TO authenticated WITH CHECK (true);
DROP POLICY IF EXISTS "sale_items_update" ON sale_items; CREATE POLICY "sale_items_update" ON sale_items FOR UPDATE TO authenticated USING (true) WITH CHECK (true);
CREATE INDEX IF NOT EXISTS idx_sale_items_sale ON sale_items(sale_id);

-- ============ PAYMENTS ============
CREATE TABLE IF NOT EXISTS payments (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  sale_id uuid NOT NULL REFERENCES sales(id) ON DELETE CASCADE,
  amount numeric(12,2) NOT NULL,
  method text NOT NULL CHECK (method IN ('mpesa_stk','mpesa_paybill')),
  status text NOT NULL DEFAULT 'initiated' CHECK (status IN ('initiated','pending','success','failed','cancelled','timeout','refunded')),
  phone text,
  mpesa_receipt_number text,
  checkout_request_id text,
  merchant_request_id text,
  account_reference text,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);
ALTER TABLE payments ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "payments_select" ON payments; CREATE POLICY "payments_select" ON payments FOR SELECT TO authenticated USING (true);
DROP POLICY IF EXISTS "payments_insert" ON payments; CREATE POLICY "payments_insert" ON payments FOR INSERT TO authenticated WITH CHECK (true);
DROP POLICY IF EXISTS "payments_update" ON payments; CREATE POLICY "payments_update" ON payments FOR UPDATE TO authenticated USING (true) WITH CHECK (true);
CREATE INDEX IF NOT EXISTS idx_payments_sale ON payments(sale_id);
CREATE INDEX IF NOT EXISTS idx_payments_checkout ON payments(checkout_request_id);

-- ============ MPESA TRANSACTIONS ============
CREATE TABLE IF NOT EXISTS mpesa_transactions (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  payment_id uuid REFERENCES payments(id) ON DELETE SET NULL,
  sale_id uuid REFERENCES sales(id) ON DELETE SET NULL,
  transaction_type text NOT NULL CHECK (transaction_type IN ('stk_push','paybill')),
  amount numeric(12,2) NOT NULL,
  phone text,
  mpesa_receipt_number text,
  checkout_request_id text,
  merchant_request_id text,
  result_code integer,
  result_desc text,
  status text NOT NULL DEFAULT 'initiated' CHECK (status IN ('initiated','pending','success','failed','cancelled','timeout')),
  reconciliation_status text NOT NULL DEFAULT 'pending' CHECK (reconciliation_status IN ('matched','unmatched','pending','failed','review')),
  callback_payload jsonb,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);
ALTER TABLE mpesa_transactions ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "mpesa_select" ON mpesa_transactions; CREATE POLICY "mpesa_select" ON mpesa_transactions FOR SELECT TO authenticated USING (true);
DROP POLICY IF EXISTS "mpesa_insert" ON mpesa_transactions; CREATE POLICY "mpesa_insert" ON mpesa_transactions FOR INSERT TO authenticated WITH CHECK (true);
DROP POLICY IF EXISTS "mpesa_update" ON mpesa_transactions; CREATE POLICY "mpesa_update" ON mpesa_transactions FOR UPDATE TO authenticated USING (true) WITH CHECK (true);
CREATE INDEX IF NOT EXISTS idx_mpesa_checkout ON mpesa_transactions(checkout_request_id);
CREATE INDEX IF NOT EXISTS idx_mpesa_receipt ON mpesa_transactions(mpesa_receipt_number);
CREATE INDEX IF NOT EXISTS idx_mpesa_created ON mpesa_transactions(created_at);

-- ============ SUPPLIERS ============
CREATE TABLE IF NOT EXISTS suppliers (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name text NOT NULL,
  contact_person text,
  phone text,
  email text,
  address text,
  outstanding_balance numeric(12,2) NOT NULL DEFAULT 0,
  created_at timestamptz DEFAULT now()
);
ALTER TABLE suppliers ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "suppliers_select" ON suppliers; CREATE POLICY "suppliers_select" ON suppliers FOR SELECT TO authenticated USING (true);
DROP POLICY IF EXISTS "suppliers_insert" ON suppliers; CREATE POLICY "suppliers_insert" ON suppliers FOR INSERT TO authenticated WITH CHECK (true);
DROP POLICY IF EXISTS "suppliers_update" ON suppliers; CREATE POLICY "suppliers_update" ON suppliers FOR UPDATE TO authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "suppliers_delete" ON suppliers; CREATE POLICY "suppliers_delete" ON suppliers FOR DELETE TO authenticated USING (true);

-- ============ PURCHASES ============
CREATE TABLE IF NOT EXISTS purchases (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  supplier_id uuid NOT NULL REFERENCES suppliers(id) ON DELETE CASCADE,
  invoice_number text,
  purchase_date date NOT NULL DEFAULT CURRENT_DATE,
  total numeric(12,2) NOT NULL DEFAULT 0,
  payment_status text NOT NULL DEFAULT 'unpaid' CHECK (payment_status IN ('paid','partial','unpaid')),
  amount_paid numeric(12,2) NOT NULL DEFAULT 0,
  balance numeric(12,2) NOT NULL DEFAULT 0,
  received_by uuid REFERENCES profiles(id) ON DELETE SET NULL,
  notes text,
  created_at timestamptz DEFAULT now()
);
ALTER TABLE purchases ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "purchases_select" ON purchases; CREATE POLICY "purchases_select" ON purchases FOR SELECT TO authenticated USING (true);
DROP POLICY IF EXISTS "purchases_insert" ON purchases; CREATE POLICY "purchases_insert" ON purchases FOR INSERT TO authenticated WITH CHECK (true);
DROP POLICY IF EXISTS "purchases_update" ON purchases; CREATE POLICY "purchases_update" ON purchases FOR UPDATE TO authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "purchases_delete" ON purchases; CREATE POLICY "purchases_delete" ON purchases FOR DELETE TO authenticated USING (true);
CREATE INDEX IF NOT EXISTS idx_purchases_supplier ON purchases(supplier_id);

-- ============ PURCHASE ITEMS ============
CREATE TABLE IF NOT EXISTS purchase_items (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  purchase_id uuid NOT NULL REFERENCES purchases(id) ON DELETE CASCADE,
  product_id uuid NOT NULL REFERENCES products(id) ON DELETE CASCADE,
  quantity integer NOT NULL,
  buying_price numeric(12,2) NOT NULL,
  subtotal numeric(12,2) NOT NULL
);
ALTER TABLE purchase_items ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "purchase_items_select" ON purchase_items; CREATE POLICY "purchase_items_select" ON purchase_items FOR SELECT TO authenticated USING (true);
DROP POLICY IF EXISTS "purchase_items_select" ON purchase_items; CREATE POLICY "purchase_items_select" ON purchase_items FOR SELECT TO authenticated USING (true);
DROP POLICY IF EXISTS "purchase_items_insert" ON purchase_items; CREATE POLICY "purchase_items_insert" ON purchase_items FOR INSERT TO authenticated WITH CHECK (true);
DROP POLICY IF EXISTS "purchase_items_update" ON purchase_items; CREATE POLICY "purchase_items_update" ON purchase_items FOR UPDATE TO authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "purchase_items_delete" ON purchase_items; CREATE POLICY "purchase_items_delete" ON purchase_items FOR DELETE TO authenticated USING (true);

-- ============ EXPENSES ============
CREATE TABLE IF NOT EXISTS expenses (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  category text NOT NULL CHECK (category IN ('Electricity','Water','Cleaning','Transport','Repairs','Maintenance','Supplies','Salaries','Other')),
  description text NOT NULL,
  amount numeric(12,2) NOT NULL,
  date date NOT NULL DEFAULT CURRENT_DATE,
  recorded_by uuid NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  attachment_url text,
  notes text,
  created_at timestamptz DEFAULT now()
);
ALTER TABLE expenses ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "expenses_select" ON expenses; CREATE POLICY "expenses_select" ON expenses FOR SELECT TO authenticated USING (true);
DROP POLICY IF EXISTS "expenses_insert" ON expenses; CREATE POLICY "expenses_insert" ON expenses FOR INSERT TO authenticated WITH CHECK (true);
DROP POLICY IF EXISTS "expenses_update" ON expenses; CREATE POLICY "expenses_update" ON expenses FOR UPDATE TO authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "expenses_delete" ON expenses; CREATE POLICY "expenses_delete" ON expenses FOR DELETE TO authenticated USING (true);
CREATE INDEX IF NOT EXISTS idx_expenses_date ON expenses(date);

-- ============ PAYROLL ============
CREATE TABLE IF NOT EXISTS payroll (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  employee_id uuid NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  basic_salary numeric(12,2) NOT NULL,
  allowances numeric(12,2) NOT NULL DEFAULT 0,
  deductions numeric(12,2) NOT NULL DEFAULT 0,
  net_salary numeric(12,2) NOT NULL,
  pay_period text NOT NULL,
  payment_status text NOT NULL DEFAULT 'pending' CHECK (payment_status IN ('paid','pending')),
  created_at timestamptz DEFAULT now()
);
ALTER TABLE payroll ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "payroll_select" ON payroll; CREATE POLICY "payroll_select" ON payroll FOR SELECT TO authenticated USING (true);
DROP POLICY IF EXISTS "payroll_insert" ON payroll; CREATE POLICY "payroll_insert" ON payroll FOR INSERT TO authenticated WITH CHECK (true);
DROP POLICY IF EXISTS "payroll_update" ON payroll; CREATE POLICY "payroll_update" ON payroll FOR UPDATE TO authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "payroll_delete" ON payroll; CREATE POLICY "payroll_delete" ON payroll FOR DELETE TO authenticated USING (true);

-- ============ AUDIT LOGS ============
CREATE TABLE IF NOT EXISTS audit_logs (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid REFERENCES profiles(id) ON DELETE SET NULL,
  action text NOT NULL,
  entity text NOT NULL,
  entity_id uuid,
  previous_value jsonb,
  new_value jsonb,
  metadata jsonb,
  created_at timestamptz DEFAULT now()
);
ALTER TABLE audit_logs ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "audit_select" ON audit_logs; CREATE POLICY "audit_select" ON audit_logs FOR SELECT TO authenticated USING (true);
DROP POLICY IF EXISTS "audit_insert" ON audit_logs; CREATE POLICY "audit_insert" ON audit_logs FOR INSERT TO authenticated WITH CHECK (true);
CREATE INDEX IF NOT EXISTS idx_audit_created ON audit_logs(created_at);
CREATE INDEX IF NOT EXISTS idx_audit_entity ON audit_logs(entity);

-- ============ SETTINGS ============
CREATE TABLE IF NOT EXISTS settings (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  key text UNIQUE NOT NULL,
  value text NOT NULL,
  category text NOT NULL DEFAULT 'general',
  updated_at timestamptz DEFAULT now()
);
ALTER TABLE settings ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "settings_select" ON settings; CREATE POLICY "settings_select" ON settings FOR SELECT TO authenticated USING (true);
DROP POLICY IF EXISTS "settings_insert" ON settings; CREATE POLICY "settings_insert" ON settings FOR INSERT TO authenticated WITH CHECK (true);
DROP POLICY IF EXISTS "settings_update" ON settings; CREATE POLICY "settings_update" ON settings FOR UPDATE TO authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "settings_delete" ON settings; CREATE POLICY "settings_delete" ON settings FOR DELETE TO authenticated USING (true);

-- ============ NOTIFICATIONS ============
CREATE TABLE IF NOT EXISTS notifications (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  type text NOT NULL,
  title text NOT NULL,
  message text NOT NULL,
  is_read boolean NOT NULL DEFAULT false,
  user_id uuid REFERENCES profiles(id) ON DELETE CASCADE,
  created_at timestamptz DEFAULT now()
);
ALTER TABLE notifications ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "notifications_select" ON notifications; CREATE POLICY "notifications_select" ON notifications FOR SELECT TO authenticated USING (true);
DROP POLICY IF EXISTS "notifications_insert" ON notifications; CREATE POLICY "notifications_insert" ON notifications FOR INSERT TO authenticated WITH CHECK (true);
DROP POLICY IF EXISTS "notifications_update" ON notifications; CREATE POLICY "notifications_update" ON notifications FOR UPDATE TO authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "notifications_delete" ON notifications; CREATE POLICY "notifications_delete" ON notifications FOR DELETE TO authenticated USING (true);

-- ============ UPDATED_AT TRIGGER ============
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trigger_tabs_updated_at ON tabs;
CREATE TRIGGER trigger_tabs_updated_at BEFORE UPDATE ON tabs FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

DROP TRIGGER IF EXISTS trigger_sales_updated_at ON sales;
CREATE TRIGGER trigger_sales_updated_at BEFORE UPDATE ON sales FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

DROP TRIGGER IF EXISTS trigger_payments_updated_at ON payments;
CREATE TRIGGER trigger_payments_updated_at BEFORE UPDATE ON payments FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

DROP TRIGGER IF EXISTS trigger_mpesa_updated_at ON mpesa_transactions;
CREATE TRIGGER trigger_mpesa_updated_at BEFORE UPDATE ON mpesa_transactions FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

DROP TRIGGER IF EXISTS trigger_settings_updated_at ON settings;
CREATE TRIGGER trigger_settings_updated_at BEFORE UPDATE ON settings FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
